In [3]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv('Crypto.csv',header=None)
data.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [5]:
transaction=[]
for i in range(data.shape[0]):
    transaction.append([str(data.values[i,j])for j in range(data.shape[1])])
transaction=np.array(transaction)
transaction

array([['BTC', 'ETH', 'XRP', 'FLM', 'VTHO ', 'AXS', 'ENJ'],
       ['ETH', 'BTC', 'ADA', 'COTI', 'HIGH', 'LTC', 'CAKE'],
       ['XVG', 'XRP', 'XVG', 'AXS', 'WRX', 'SOL', 'BAKE'],
       ['ENJ', 'TRX', 'WRX', 'DOT', 'ETH', 'USDT', 'AVAX'],
       ['TRX', 'ADA', 'DOGE', 'SAND', 'BTC', 'VET', 'COTI'],
       ['ADA', 'ENJ', 'SHIB', 'SHIB', 'CAKE', 'DOT', 'ETH'],
       ['XRP', 'BNB', 'WRX', 'DOGE', 'BAKE', 'AVAX', 'BTC'],
       ['BNB', 'WRX', 'SAND', 'XEM', 'CAKE', 'AVAX', 'FLM'],
       ['WRX', 'SAND', 'COTI', 'HIGH', 'LINK', 'AVAX', 'XEM'],
       ['AXS', 'META', 'TRX', 'VTHO', 'XRP', 'ENJ', 'XEM'],
       ['XRP', 'AXS', 'ADA', 'SHIB', 'ETH', 'WRX', 'SHIB'],
       ['ADA', 'LTC', 'XRP', 'WRX', 'BTC', 'DOGE', 'DOGE'],
       ['XVG', 'SOL', 'BNB', 'SAND', 'CAKE', 'SHIB', 'XEM'],
       ['WRX', 'USDT', 'WRX', 'COTI', 'COTI', 'WRX', 'HIGH'],
       ['DOGE', 'VET', 'AXS', 'WRX', 'ETH', 'SAND', 'VTHO'],
       ['SHIB', 'DOT', 'XRP', 'SAND', 'BTC', 'COTI', 'SHIB'],
       ['WRX', 'AVAX', 'ADA', 'META', 'FLM', 'TRX', 'WRX'],
       ['SAND', 'AVAX', 'XVG', 'AXS', 'WRX', 'ADA', 'SAND'],
       ['COTI', 'AVAX', 'WRX', 'LTC', 'SAND', 'XRP', 'COTI'],
       ['FLM', 'ENJ', 'AVAX', 'SOL', 'COTI', 'BNB', 'WRX'],
       ['AVAX', 'DOT', 'AVAX', 'BAKE', 'ETH', 'WRX', 'META'],
       ['AVAX', 'SAND', 'AVAX', 'CAKE', 'BTC', 'SAND', 'AXS'],
       ['ENJ', 'SHIB', 'ENJ', 'LINK', 'CAKE', 'COTI', 'LTC'],
       ['WRX', 'XRP', 'DOT', 'XRP', 'ADA', 'TRX', 'SOL']], dtype='<U5')

In [6]:
te=TransactionEncoder()
te_ary=te.fit(transaction).transform(transaction)
dataset=pd.DataFrame(te_ary,columns=te.columns_)
dataset

,ADA,AVAX,AXS,BAKE,BNB,BTC,CAKE,COTI,DOGE,DOT,...,SOL,TRX,USDT,VET,VTHO,VTHO,WRX,XEM,XRP,XVG
0,False,False,True,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
1,True,False,False,False,False,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,True,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,True,True
3,False,True,False,False,False,False,False,False,False,True,...,False,True,True,False,False,False,True,False,False,False
4,True,False,False,False,False,True,False,True,True,False,...,False,True,False,True,False,False,False,False,False,False
5,True,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
6,False,True,False,True,True,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
7,False,True,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,True,True,False,False
8,False,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,True,False,False
9,False,False,True,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,True,False
10,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
11,True,False,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
12,False,False,False,False,True,False,True,False,False,False,...,True,False,False,False,False,False,False,True,False,True
13,False,False,False,False,False,False,False,True,False,False,...,False,False,True,False,False,False,True,False,False,False
14,False,False,True,False,False,False,False,False,True,False,...,False,False,False,True,True,False,True,False,False,False
15,False,False,False,False,False,True,False,True,False,True,...,False,False,False,False,False,False,False,False,True,False
16,True,True,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,True,False,False,False
17,True,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
18,False,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
19,False,True,False,False,True,False,False,True,False,False,...,True,False,False,False,False,False,True,False,False,False
20,False,True,False,True,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
21,False,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
23,True,False,False,False,False,False,False,False,False,True,...,True,True,False,False,False,False,True,False,True,False

In [7]:
dataset.shape

(24, 29)

In [8]:
dataset.columns

Index(['ADA', 'AVAX', 'AXS', 'BAKE', 'BNB', 'BTC', 'CAKE', 'COTI', 'DOGE',
       'DOT', 'ENJ', 'ETH', 'FLM', 'HIGH', 'LINK', 'LTC', 'META', 'SAND',
       'SHIB', 'SOL', 'TRX', 'USDT', 'VET', 'VTHO', 'VTHO ', 'WRX', 'XEM',
       'XRP', 'XVG'],
      dtype='object')

In [9]:
def encode_units(x):
    if x==False:
        return 0;
    if x==True:
        return 1;
dataset=dataset.applymap(encode_units)
dataset.head()

,ADA,AVAX,AXS,BAKE,BNB,BTC,CAKE,COTI,DOGE,DOT,...,SOL,TRX,USDT,VET,VTHO,VTHO,WRX,XEM,XRP,XVG
0,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
1,1,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,1,1
3,0,1,0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,1,0,0,0
4,1,0,0,0,0,1,0,1,1,0,...,0,1,0,1,0,0,0,0,0,0

In [11]:
frequent_itemset=apriori(dataset,min_support=0.05,use_colnames=True)

frequent_itemset['length']=frequent_itemset['itemsets'].apply(lambda x:len(x))
frequent_itemset.head()

    support itemsets  length
0  0.333333    (ADA)       1
1  0.416667   (AVAX)       1
2  0.291667    (AXS)       1
3  0.125000   (BAKE)       1
4  0.166667    (BNB)       1

In [12]:
frequent_itemset.tail()

      support                 itemsets  length
195  0.083333  (AVAX, COTI, SAND, WRX)       4
196  0.083333    (AVAX, ETH, DOT, WRX)       4
197  0.083333   (AVAX, SAND, XEM, WRX)       4
198  0.083333   (XEM, BNB, CAKE, SAND)       4
199  0.083333    (BTC, DOGE, XRP, WRX)       4

In [31]:
frequent_itemset[(frequent_itemset['length']==2)].head()

    support     itemsets  length
29     0.10  (ADA, AVAX)       2
30     0.10   (ADA, AXS)       2
31     0.15   (BTC, ADA)       2
32     0.10  (CAKE, ADA)       2
33     0.10  (ADA, COTI)       2

In [13]:
rules=association_rules(frequent_itemset,metric='lift',min_threshold=1.4)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(DOGE),(ADA),0.166667,0.333333,0.083333,0.500000,1.500000,0.027778,1.333333
1,(ADA),(DOGE),0.333333,0.166667,0.083333,0.250000,1.500000,0.027778,1.111111
2,(LTC),(ADA),0.166667,0.333333,0.083333,0.500000,1.500000,0.027778,1.333333
3,(ADA),(LTC),0.333333,0.166667,0.083333,0.250000,1.500000,0.027778,1.111111
4,(TRX),(ADA),0.208333,0.333333,0.125000,0.600000,1.800000,0.055556,1.666667
...,...,...,...,...,...,...,...,...,...
427,"(XRP, WRX)","(BTC, DOGE)",0.250000,0.125000,0.083333,0.333333,2.666667,0.052083,1.312500
428,(BTC),"(DOGE, XRP, WRX)",0.291667,0.083333,0.083333,0.285714,3.428571,0.059028,1.283333
429,(DOGE),"(BTC, XRP, WRX)",0.166667,0.083333,0.083333,0.500000,6.000000,0.069444,1.833333
430,(XRP),"(BTC, DOGE, WRX)",0.375000,0.083333,0.083333,0.222222,2.666667,0.052083,1.178571
431,(WRX),"(BTC, DOGE, XRP)",0.625000,0.083333,0.083333,0.133333,1.600000,0.031250,1.057692

In [22]:
rules['antecedents_length']=rules['antecedents'].apply(lambda x:len(x))
rules['consequents_length']=rules['consequents'].apply(lambda x:len(x))
rules.sort_values('lift',ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,consequents_length,antecedents_length
425,"(DOGE, XRP)","(BTC, WRX)",0.083333,0.083333,0.083333,1.000000,12.000000,2,2
424,"(BTC, WRX)","(DOGE, XRP)",0.083333,0.083333,0.083333,1.000000,12.000000,2,2
308,"(DOGE, SAND)",(VET),0.083333,0.083333,0.083333,1.000000,12.000000,1,2
412,"(BNB, SAND)","(CAKE, XEM)",0.083333,0.083333,0.083333,1.000000,12.000000,2,2
309,(VET),"(DOGE, SAND)",0.083333,0.083333,0.083333,1.000000,12.000000,2,1
...,...,...,...,...,...,...,...,...,...
0,(DOGE),(ADA),0.166667,0.333333,0.083333,0.500000,1.500000,1,1
17,(ETH),(AXS),0.291667,0.291667,0.125000,0.428571,1.469388,1,1
16,(AXS),(ETH),0.291667,0.291667,0.125000,0.428571,1.469388,1,1
15,(WRX),(AVAX),0.625000,0.416667,0.375000,0.600000,1.440000,1,1
14,(AVAX),(WRX),0.416667,0.625000,0.375000,0.900000,1.440000,1,1

In [23]:
rules.drop(rules.columns[[7,8]],axis=1,inplace=True)

In [28]:
rules.sort_values('support',ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
15,(WRX),(AVAX),0.625000,0.416667,0.375000,0.600000,1.440000
14,(AVAX),(WRX),0.416667,0.625000,0.375000,0.900000,1.440000
192,"(SAND, WRX)",(AVAX),0.208333,0.416667,0.166667,0.800000,1.920000
193,(AVAX),"(SAND, WRX)",0.416667,0.208333,0.166667,0.400000,1.920000
21,(XRP),(AXS),0.375000,0.291667,0.166667,0.444444,1.523810
...,...,...,...,...,...,...,...
170,"(AVAX, DOT)",(WRX),0.083333,0.625000,0.083333,1.000000,1.600000
169,(DOT),"(AVAX, ETH)",0.208333,0.083333,0.083333,0.400000,4.800000
168,(ETH),"(AVAX, DOT)",0.291667,0.083333,0.083333,0.285714,3.428571
167,(AVAX),"(ETH, DOT)",0.416667,0.125000,0.083333,0.200000,1.600000
431,(WRX),"(BTC, DOGE, XRP)",0.625000,0.083333,0.083333,0.133333,1.600000

In [25]:
rules.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift'],
      dtype='object')